# Generated by Django 3.1.6 on 2021-03-12 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('image', models.FileField(upload_to='static/uploads/gallery')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(4)])),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='static/uploads/menu')),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Deserts', 'Deserts'), ('WineCard', 'WineCard'), ('Drinks&Tea', 'Drinks&Tea')], max_length=200, validators=[django.core.validators.MinLengthValidator(4)])),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
