# Generated by Django 3.1.6 on 2021-03-13 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0003_auto_20210312_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('image', models.FileField(upload_to='static/images/uploads/gallery')),
                ('detail', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(50)])),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
