# Generated by Django 3.1.6 on 2021-03-13 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0004_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('phone', models.IntegerField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('event_type', models.CharField(choices=[('Weddings', 'Weddings'), ('Birthday Parties', 'Birthday Parties'), ('Anniversary Parties', 'Anniversary Parties'), ('Business Meetings', 'Business Meetings'), ('Conferences', 'Conferences'), ('Luncheons', 'Luncheons'), ('Holiday Gatherings', 'Holiday Gatherings'), ('Other', 'Other')], max_length=50)),
                ('catering_type', models.CharField(choices=[('On-promise', 'On-promise'), ('Off-promise', 'Off-promise')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(10)])),
                ('catering_order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.FileField(upload_to='static/images/uploads/stories'),
        ),
    ]
