# Generated by Django 3.1.6 on 2021-03-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0006_auto_20210313_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.IntegerField(),
        ),
    ]
