# Generated by Django 3.1.6 on 2021-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0007_auto_20210313_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
    ]
