# Generated by Django 3.1.6 on 2021-03-14 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0008_auto_20210313_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering',
            name='complition',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='complition',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catering',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='catering',
            name='catering_order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='catering',
            name='catering_type',
            field=models.CharField(choices=[('On-promise', 'On-promise'), ('Off-promise', 'Off-promise')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catering',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='catering',
            name='event_type',
            field=models.CharField(choices=[('Weddings', 'Weddings'), ('Birthday Parties', 'Birthday Parties'), ('Anniversary Parties', 'Anniversary Parties'), ('Business Meetings', 'Business Meetings'), ('Conferences', 'Conferences'), ('Luncheons', 'Luncheons'), ('Holiday Gatherings', 'Holiday Gatherings'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catering',
            name='name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='catering',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='catering',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(max_length=10, null=True),
        ),
    ]
