# Generated by Django 3.1.6 on 2021-03-14 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0009_auto_20210314_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='address',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='catering',
            name='complition',
            field=models.BooleanField(null=True),
        ),
    ]
