# Generated by Django 3.1.6 on 2021-03-16 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0012_auto_20210316_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catering',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.AddField(
            model_name='catering',
            name='firstname',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='catering',
            name='lastname',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='firstname',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='lastname',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
