# Generated by Django 3.1.6 on 2021-03-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0013_auto_20210316_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='completion',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
