# Generated by Django 3.1.6 on 2021-03-20 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0014_auto_20210319_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)])),
                ('completion', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='catering',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
