# Generated by Django 3.1.6 on 2021-03-20 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0015_auto_20210320_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catering',
            name='username',
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='firstname',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='message',
            name='lastname',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='order',
            name='firstname',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='order',
            name='lastname',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
