# Generated by Django 3.1.6 on 2021-03-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0017_auto_20210320_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
