# Generated by Django 3.1.6 on 2021-03-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0025_auto_20210323_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
