# Generated by Django 3.1.6 on 2021-03-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0030_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='foodname',
        ),
        migrations.AddField(
            model_name='cart',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Nd.menu'),
        ),
    ]
