# Generated by Django 3.1.6 on 2021-03-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0031_auto_20210325_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menu',
            new_name='foodname',
        ),
    ]
