# Generated by Django 3.1.6 on 2021-03-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0033_auto_20210325_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='foodname',
        ),
    ]
