# Generated by Django 3.1.6 on 2021-03-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0034_remove_order_foodname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='foodname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Nd.menu'),
        ),
    ]
