# Generated by Django 3.1.6 on 2021-03-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0035_order_foodname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
