# Generated by Django 3.1.6 on 2021-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0036_auto_20210325_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
