# Generated by Django 3.1.6 on 2021-03-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nd', '0037_auto_20210325_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
